refactor: ensuring TARGET and MIRROR exist

diff --git a/scripts/gitlab-mirror/mirror b/scripts/gitlab-mirror/mirror
--- a/scripts/gitlab-mirror/mirror
+++ b/scripts/gitlab-mirror/mirror
@@ -7,6 +7,11 @@
 DELAY=${1:-60}
 SSH_KEY=${2:-/root/.ssh/gitlab-mirror}
 
+if ! ( [ -n "$TARGET" ] && [ -n "$MIRROR" ] ) ; then
+  echo "TARGET and/or MIRROR missing"
+  exit 1
+fi
+
 # Set up ssh and add a valid key
 eval `ssh-agent -s`
 ssh-add $SSH_KEY
@@ -23,8 +28,7 @@ do
 git remote update --prune
 
 # Start Gitlab's pull mirroring process
-if [ -n "$GITLAB_PROJECT_ID" ]
-then
+if [ -n "$GITLAB_PROJECT_ID" ] ; then
   curl --header "Private-Token: $GITLAB_PERSONAL_ACCESS_TOKEN" -X POST  "https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/mirror/pull/" && echo ""
 fi
 
